name: Create Source Archive
on:
  workflow_dispatch:
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: 5488984d20e0dbfe4be2c3ba8fb18eb81a5e0e8b
      - name: Create tar.gz
        run: git archive --format=tar.gz --prefix=webkit/ HEAD -o webkit-source-5488984.tar.gz
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: webkit-source-5488984.tar.gz
          tag_name: source-archive-5488984
